[project]
name = "ledmonitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "bleak>=1.1.0",
    "hardwaremonitor>=1.0.0",
    "pydantic>=2.11.7",
    "pywin32>=311",
]
